return {
  source = {
    url = "https://git.suckless.org/sbase",
    mirror = "https://git.internal/mirrors/sbase",
    commit = "c546c3a5724c81cee9a11d816a38ccdf17472129",
  },
  license = "MIT AND ISC AND BSD-3-Clause AND Unicode-3.0",
  dependencies = {
    host = { "make" },
    pyxis = { "libc", "libpyxis" },
  },
  patches = {
    "patches/0001-narrow-cksum-helper-header.patch",
    "patches/0002-restrict-tee-options-and-close-outputs.patch",
    "patches/0003-declare-uniq-helpers.patch",
    "patches/0004-declare-wc-tail-sort-helpers.patch",
    "patches/0005-refuse-tail-follow.patch",
  },
  outputs = {
    executable = "bin/cksum.pxe",
    tee = "bin/tee.pxe",
    uniq = "bin/uniq.pxe",
    sha256sum = "bin/sha256sum.pxe",
    wc = "bin/wc.pxe",
    tail = "bin/tail.pxe",
    sort = "bin/sort.pxe",
    license = "share/licenses/sbase/LICENSE",
    argument_notice = "share/licenses/sbase/arg.h",
    strtonum_notice = "share/licenses/sbase/strtonum.c",
    memmem_notice = "share/licenses/sbase/memmem.c",
    reallocarray_notice = "share/licenses/sbase/reallocarray.c",
    queue_notice = "share/licenses/sbase/queue.h",
    unicode_notice = "share/licenses/sbase/unicode-license.txt",
  },
}
