return {
  ["ca-certificates"] = "ca-certificates",
  busybox = "busybox",
  doom = "doom",
  fastfetch = "fastfetch",
  fmt = "fmt",
  kilo = "kilo",
  links = "links",
  libpng = "libpng",
  lua = "lua",
  mbedtls = "mbedtls",
  pciids = "pciids",
  picohttpparser = "picohttpparser",
  quake = "quake",
  sbase = "sbase",
  tcc = "tcc",
  tzdata = "tzdata",
  usbids = "usbids",
  zlib = "zlib",
}
