/* BusyBox less feature selection, without Kconfig.
 * SPDX-License-Identifier: GPL-2.0-only */
#ifndef PYXIS_BUSYBOX_LESS_CONFIG_H
#define PYXIS_BUSYBOX_LESS_CONFIG_H

#define CONFIG_FEATURE_LESS_MAXLINES 9999999
#define ENABLE_FEATURE_LESS_REGEXP 1
#define ENABLE_FEATURE_LESS_FLAGS 1
#define ENABLE_FEATURE_LESS_MARKS 0
#define ENABLE_FEATURE_LESS_BRACKETS 0
#define ENABLE_FEATURE_LESS_TRUNCATE 0
#define ENABLE_FEATURE_LESS_WINCH 0
#define ENABLE_FEATURE_LESS_ASK_TERMINAL 0
#define ENABLE_FEATURE_LESS_DASHCMD 0
#define ENABLE_FEATURE_LESS_LINENUMS 0
#define ENABLE_FEATURE_LESS_RAW 0
#define ENABLE_FEATURE_LESS_ENV 0

#define IF_FEATURE_LESS_REGEXP(...) __VA_ARGS__
#define IF_FEATURE_LESS_TRUNCATE(...)
#define IF_FEATURE_LESS_RAW(...)
#define IF_FEATURE_LESS_ASK_TERMINAL(...)

#endif
